variables:
  DOCKER_IMAGENAME_DB_SERVICE: "mitrjain1996/sbs-db"
  DOCKER_VERSION: "latest"

stages:
  - build

build_image:
  stage: build
  image: docker:24.0.7-cli
  services:
   - docker:24.0.7-dind
  variables:
   DOCKER_TLS_CERTDIR: "/certs"
  before_script:
   - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  script:
   - docker build -t $DOCKER_IMAGENAME_DB_SERVICE:$DOCKER_VERSION ./database/

   - docker push $DOCKER_IMAGENAME_DB_SERVICE:$DOCKER_VERSION
