version: '1'
services:
  sbs-db:
    build:
      context: ../database
      dockerfile: ./Dockerfile
    env_file: ./env-sbs-db
    ports:
      - 5432:5432
  
  sbs-api-server:
    build:
      context: ../backend
      dockerfile: ./Dockerfile
    depends_on:
      - sbs-db
    env_file: ./env-sbs-api-server
    ports:
      - 4000:4000

  sbs-frontend:
    build:
      context: ../../student-booking-system
      dockerfile: ./Dockerfile
    depends_on:
      - sbs-api-server
    env_file: ./env-sbs-frontend
    ports:
      - 8080:3000
  
  # nginx-router:
  #   ports:
  #     - 8081:8081
  #   build:
  #     context: ../nginx
  #     dockerfile: ./Dockerfile
  #   depends_on:
  #     - students-api-server